# Generated by Django 3.2.3 on 2021-05-22 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0004_team_yt_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basedetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('photo', models.CharField(max_length=200)),
                ('fb_link', models.CharField(max_length=400)),
                ('instagram_link', models.CharField(max_length=200)),
                ('twitter_link', models.CharField(max_length=200)),
                ('yt_link', models.CharField(max_length=200)),
            ],
        ),
    ]
