# Generated by Django 3.2.3 on 2021-05-22 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0006_rename_photo_basedetail_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Basedetail',
        ),
    ]
