# Generated by Django 3.2.3 on 2021-05-22 04:59

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0008_aboutpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
